VAL = 'val'
SUM = 'sum'
AVG = 'avg'
MIN = 'min'
MAX = 'max'
PEER_GROUP_SIZE = 15
WINDOW_SIZE = 3
TRACE_START = 'trace_start'
TRACE_END = 'trace_end'
TRACE_DURATION = TIME_FROM_TRACE_START = 'trace_duration'
TIME_FROM_PREVIOUS_EVENT = 'time_from_previous_event'
CUMSUM = '_cumsum'
CUMAVG = '_cumavg'
MW_SUM = '_mw_sum'
MW_AVG = '_mw_avg'
UNIQUE_ACTIVITIES = 'unique_activities'
ACTIVITIES_MEAN = 'activity_occurrences_mean'
ACTIVITIES_STD = 'activity_occurrences_std'
ACTIVITY_OCCURRENCE = 'activity_occurrence'
TRACE_LENGTH = INDEX = 'trace_length'
